language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lcskoerner/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lcskoerner/docker-react yarn test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-2"
  env: "Dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-728027380745"
  bucket_path: "docker-react2"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
